Fix

diff --git a/.github/workflows/promptflow-import-linter.yml b/.github/workflows/promptflow-import-linter.yml
--- a/.github/workflows/promptflow-import-linter.yml
+++ b/.github/workflows/promptflow-import-linter.yml
@@ -59,4 +59,15 @@ jobs:
         cd ${{ env.WORKING_DIRECTORY }}/src/promptflow-evals
         poetry run lint-imports
       working-directory: ${{ env.WORKING_DIRECTORY }}
+    - name: import lint testing private imports from global
+      run: |
+        set -xe
+        cd ${{ env.WORKING_DIRECTORY }}/src/promptflow-azure
+        echo "=== Add more import linter when facing more import errors ==="
+
+        echo "=== promptflow-devkit ==="
+        poetry run python -c $'from promptflow._sdk import *\nfrom promptflow._cli import *'
+
+        echo "=== promptflow-azure ==="
+        poetry run python -c $'from promptflow.azure._cli import *\nfrom promptflow.azure import *'
 
