Refine spell check ci

diff --git a/.github/workflows/spell_check.yml b/.github/workflows/spell_check.yml
--- a/.github/workflows/spell_check.yml
+++ b/.github/workflows/spell_check.yml
@@ -26,5 +26,11 @@ jobs:
 
       - name: Run cspell
         run: |-
-          cspell lint "**"
-          echo -e "\e[91mNote: If the detected words are expected, add them into ".cspell.json" which is at the repo root folder.\e[0m" 
+          cspell lint "**" > cspell_check.log
+          if [ -s cspell_check.log ]; then
+            echo -e "\e[91mNote: If the detected words are expected, add them into ".cspell.json" which is at the repo root folder.\e[0m" 
+            echo -e "====================== Summary of cspell errors ======================"
+            echo -e "\e[31m$(cat cspell_check.log)\e[0m" 
+            exit 1
+          fi
+          
